name: AWS CI and CD
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions: 
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install node.js 
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Check the code quality
        run: npm run lint     
      - name: Build the project
        run: npm run build
      - name: Build an Docker image
        run: docker build -t aws-app-web:latest .
      - name: Tag Docker image for Docker hub
        run: docker tag aws-app-web:latest arturs85/frontend:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: docker push arturs85/frontend:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::849381698744:role/HitHubSSM-role
          aws-region: eu-north-1

      - name: Deploy to EC2 via SSM
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          aws ssm send-command \
          --instance-ids "i-01f7f7498fb2a63ba" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[
            \"echo '$DOCKERHUB_TOKEN' | sudo docker login -u '$DOCKERHUB_USERNAME' --password-stdin\",
            \"sudo docker pull arturs85/frontend:latest\",
            \"sudo docker stop aws-web-container || true\",
            \"sudo docker rm aws-web-container || true\",
            \"sudo docker run -d -p 80:80 --name aws-web-container arturs85/frontend:latest\"
          ]" \
          --region eu-north-1
          
     
